flyway.connectRetries=3
flyway.connectRetriesInterval=5
flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true
flyway.placeholderReplacement=false
flyway.sqlMigrationSuffixes=.sql
flyway.cleanDisabled=true
