ALTER TABLE temp_data
    ADD COLUMN source VARCHAR(100) NULL,
    ADD COLUMN is_processed TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
