flyway.url=jdbc:mysql://localhost:3309/demo?allowPublicKeyRetrieval=true&useSSL=false
flyway.user=root
flyway.password=root
flyway.locations=filesystem:/flyway/project/migrations
flyway.connectRetries=30
flyway.validateMigrationNaming=true
flyway.baselineOnMigrate=true
flyway.target=9
